# 开发环境
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  redis:
    database: 0
    host: localhost
    port: 6379

security:
  oauth2:
    client:
      client-id: demo-app
      client-secret: 123456
      user-authorization-uri: http://localhost:8101/oauth/authorize
      access-token-uri: http://localhost:8101/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8101/oauth/token_key
        key-value: dev


logging:
  level:
    com.tsien: debug
server:
  port: 8111

