# 开发环境
spring:
  datasource:
    druid:
      name: druidDatasource
      url: jdbc:mysql://localhost:3306/mall_swarm?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: QWer!@34

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  redis:
    database: 0
    host: localhost
    port: 6379

logging:
  level:
    com.tsien: debug
server:
  port: 8101
